# Arquivo de configuração do Railway
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Variáveis de ambiente serão definidas no painel do Railway
# DATABASE_URL será fornecida automaticamente pelo Railway PostgreSQL
# PORT será definida automaticamente pelo Railway